version: '3.7'

# Definimos dos volumenes nombrado (odoo_conf) pero que esté enlazado a una
# carpeta. De esta manera es posible realizar copias sobre él desde el host
# en la construcción de la imagen y además posteriormente acceder a ellas 
# desde el host.
# Un volumen enlazado directamente host:contenedor elimina todo lo que 
# haya en esa carpeta del contenedor 
volumes:
  odoo_conf:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${SERVER_INFO_PATH_HOST}/odoo/config

  odoo_addons:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${APP_MODULE_PATH_HOST}

  odoo_data: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_PATH_HOST}/odoo
      
  mariadb_data:
    driver: local

  moodle_data:
    driver: local

  moodledata_data:
    driver: local
      
services:
  #############################
  ## ODOO #####################
  #############################
  # Definimos el servicio Web, en este caso Odoo
  web:
    build:
      # donde está el código pasra construir la imagen
      context: ./odoo
      # valores que pueden ser utilizados en la construcción de la imagen
      args:
          - ODOO_VERSION=${ODOO_VERSION}
          - ODOO_SHELL_OH_MY_ZSH=${ODOO_SHELL_OH_MY_ZSH}
          - ODOO_INSTALL_GIT=${ODOO_INSTALL_GIT}
          - ODOO_INSTALL_SSH=${ODOO_INSTALL_SSH}
          - ODOO_INSTALL_SSL_DEV=${ODOO_INSTALL_SSL_DEV}
          - ODOO_INSTALL_PDFTK=${ODOO_INSTALL_PDFTK}
       
    # Port Mapping: indicamos que el puerto 8069 del contenedor se mapeara con 
    # el puerto ODOO_PORT en el anfritrion
    # Permitiendo acceder a Odoo mediante http://localhost:ODOO_PORT
    # Además mapeamos el puerto 22 para ssh
    ports:
      - "${ODOO_SSH_PORT}:22"
      - "${ODOO_PORT}:8069"

    # permito tener el contenedor vivo. Al eliminar el punto de entrada una vez arranca se para
    # con tty: true puedo entrar y trabajar sobre él.
    tty: true

    # Indicamos que depende de "db", por lo cual debe ser procesada primero "db"
    depends_on:
      - db

    # Definimos variables de entorno de Odoo
    environment:
      # conexión con Postgress
      - HOST=${ODOO_POSTGRESS_HOST}
      - USER=${ODOO_POSTGRESS_USER}
      - PASSWORD=${ODOO_POSTGRESS_PASSWORD}
      - PORT=${ODOO_POSTGRESS_PORT}

    # Mapeamos el directorio de los modulos (como por ejemplo "/mnt/extra-addons")
    # en un directorio local, por defecto en el carpeta ../addons del directorio 
    # donde se ejecuta docker-compose
    volumes:
      - odoo_addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
      - ${SERVER_INFO_PATH_HOST}/odoo/logs:/var/log/odoo
      - ${SERVER_INFO_PATH_HOST}/odoo/repo:${REPO_PATH_CONTAINER}    
      - odoo_conf:/etc/odoo

    deploy:
      restart_policy:
        condition: any
        delay: 0s

  #################################
  ## POSTGRES #####################
  #################################
  # Definimos el servicio de la base de datos
  db:
    build:
      context: ./postgres
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
        - POSTGRES_IMAGE=${POSTGRES_IMAGE}
        
    ports:
      - "${POSTGRES_PORT}:5432"

    # Definimos variables de entorno de PostgreSQL
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    # Mapeamos el directorio del contenedor "var/lib/postgresql/data" en un directorio local
    # por defecto en la carpeta .odoodock del home del usuario
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data

    
  #################################
  ## MOODLE #######################
  #################################
  # Definimos el servicio de Moodle
  moodle:
    build:
      context: ./moodle
      args:
        - MOODLE_VERSION=${MOODLE_VERSION}

    ports:
       - "${MOODLE_PORT}:8080"
       - "${MOODLE_SSL_PORT}:8443"

    environment:
      - ALLOW_EMPTY_PASSWORD=${MOODLE_ALLOW_EMPTY_PASSWORD}
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      # tipo de base de datos. Por ahora sólo mariadb
      - MOODLE_DATABASE_TYPE=${MOODLE_DATABASE_TYPE}
      # el contenedor de la base de datos
      - MOODLE_DATABASE_HOST=${MOODLE_DATABASE_HOST}
      - MOODLE_DATABASE_PORT_NUMBER=${MOODLE_DATABASE_PORT_NUMBER}
      - MOODLE_DATABASE_USER=${MOODLE_DATABASE_USER}
      - MOODLE_DATABASE_NAME=${MOODLE_DATABASE_NAME}
      - MOODLE_DATABASE_PASSWORD=${MOODLE_DATABASE_PASSWORD}

    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'

    depends_on:
      - mariadb-moodle

  #############################
  ## MARIADB ##################
  #############################
  mariadb-moodle:
    build:
      context: ./mariadb
      args:
        - MARIADB_VERSION=${MARIADB_MOODLE_VERSION}
        
    environment:
      - ALLOW_EMPTY_PASSWORD=${MARIADB_MOODLE_ALLOW_EMPTY_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_MOODLE_ROOT_PASSWORD}
      - MARIADB_PASSWORD=${MARIADB_MOODLE_PASSWORD}
      - MARIADB_USER=${MARIADB_MOODLE_USER}
      - MARIADB_DATABASE=${MARIADB_MOODLE_DATABASE}
      - MARIADB_CHARACTER_SET=${MARIADB_MOODLE_CHARACTER_SET}
      - MARIADB_COLLATE=${MARIADB_MOODLE_COLLATE}

    volumes:
      - 'mariadb_data:/bitnami/mariadb'
